name: Deploy

on:
  push:
    branches:
      - main  # O la rama en la que deseas que se ejecute el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar la clave SSH para el despliegue
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      # 3. Ejecutar comandos de despliegue directamente
      - name: Deploy to server
        run: |
          echo "Iniciando despliegue..."
          
          # Comandos de despliegue: (Ejemplo para un proyecto Node.js)
          # Clona el repositorio si no está ya presente en el servidor
          git clone https://github.com/evelynnpxe/Babashka-Pod-Docker.git
          cd Babashka-Pod-Docker
          
          # Instalar dependencias (si aplica)
          npm install
          
          # Construir proyecto (si aplica)
          npm run build
          
          # Reiniciar servicios (si es necesario, ajustar el nombre del servicio)
          sudo systemctl restart nombre_del_servicio
          
          echo "Despliegue completo"

